export const mockPartners = [
    {
        _id: '5ff7225bc912646c3fb2c1ee',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'voluptate',
        color: 'green',
        description: 'ipsum excepteur ex elit amet aliqua nisi consequat sunt ipsum minim nulla',
        category: 'sport',
    },
    {
        _id: '5ff7225bfd5b0939165f7100',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'ea',
        color: 'brown',
        description: 'minim ex commodo do aliqua anim sit irure proident magna et exercitation',
        category: 'wine',
    },
    {
        _id: '5ff7225b8d1cdec931dcaf0f',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'non',
        color: 'green',
        description: 'in aute qui laborum in ex minim sint cillum non culpa cillum',
        category: 'wine',
    },
    {
        _id: '5ff7225b783a82b3590ff0ae',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'elit',
        color: 'blue',
        description: 'consequat aliqua tempor incididunt ut sunt officia culpa laborum do occaecat cupidatat',
        category: 'sport',
    },
    {
        _id: '5ff7225bea61b20c71e7b25c',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'ipsum',
        color: 'blue',
        description: 'Lorem cillum cillum ipsum ullamco proident excepteur sunt deserunt excepteur do laboris',
        category: 'wine',
    },
    {
        _id: '5ff7225bea151d51042720f1',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'esse',
        color: 'blue',
        description: 'ipsum aliquip est pariatur do voluptate sunt pariatur culpa labore occaecat quis',
        category: 'sport',
    },
    {
        _id: '5ff7225bf172b62296ab1d80',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'in',
        color: 'green',
        description: 'magna quis cupidatat magna Lorem consequat est voluptate non laborum excepteur labore',
        category: 'sport',
    },
    {
        _id: '5ff7225b80ac76e78132d8c9',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'non',
        color: 'brown',
        description: 'cillum non aliquip occaecat ad esse non proident nostrud dolore irure esse',
        category: 'wine',
    },
    {
        _id: '5ff7225b99960513bce434ee',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'reprehenderit',
        color: 'green',
        description: 'exercitation velit consectetur voluptate ex voluptate dolore non tempor laborum occaecat non',
        category: 'sport',
    },
    {
        _id: '5ff7225bc57debe0cf84a93f',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'ut',
        color: 'blue',
        description: 'ea laboris ullamco anim aliquip tempor irure voluptate elit culpa laborum cillum',
        category: 'wine',
    },
    {
        _id: '5ff7225b5099b0902dc8de5a',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'aute',
        color: 'brown',
        description: 'nisi cillum esse id incididunt cillum consequat eu velit eu nulla dolor',
        category: 'sport',
    },
    {
        _id: '5ff7225b8d7808ed2123a84d',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'aute',
        color: 'green',
        description: 'excepteur ipsum enim minim deserunt elit veniam consectetur ut velit eiusmod occaecat',
        category: 'wine',
    },
    {
        _id: '5ff7225b3405cf98ff077278',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'enim',
        color: 'brown',
        description: 'adipisicing deserunt laboris ullamco culpa enim laboris quis cupidatat cillum laboris aute',
        category: 'sport',
    },
    {
        _id: '5ff7225ba93f336737bf24a3',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'id',
        color: 'blue',
        description: 'id pariatur excepteur reprehenderit ex cupidatat nisi ut eiusmod eiusmod minim ullamco',
        category: 'sport',
    },
    {
        _id: '5ff7225bedf9ed984a5248d2',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'in',
        color: 'brown',
        description: 'occaecat commodo nisi commodo ut nostrud ex nulla exercitation eiusmod eiusmod labore',
        category: 'sport',
    },
    {
        _id: '5ff7225becc5b08922c710f8',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'enim',
        color: 'brown',
        description: 'aliquip est cupidatat ex aliqua cillum ut cupidatat enim duis esse aute',
        category: 'sport',
    },
    {
        _id: '5ff7225be0ac650458d0b49e',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'aliquip',
        color: 'green',
        description: 'qui excepteur ad quis proident laboris id in ipsum aute officia ullamco',
        category: 'wine',
    },
    {
        _id: '5ff7225b96f70a6a0a6830a8',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'dolor',
        color: 'blue',
        description: 'ullamco nostrud ad qui fugiat est pariatur dolor non do deserunt laborum',
        category: 'wine',
    },
    {
        _id: '5ff7225b6de06564ff078140',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'laborum',
        color: 'blue',
        description: 'tempor amet ullamco sint ad qui sunt cupidatat nostrud esse aliquip do',
        category: 'sport',
    },
    {
        _id: '5ff7225bf1fb8421e195ccf0',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'ut',
        color: 'green',
        description: 'duis pariatur eiusmod aliqua occaecat in culpa elit laborum ex consequat ut',
        category: 'sport',
    },
    {
        _id: '5ff7225bbd7bb7d2b968a414',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'magna',
        color: 'blue',
        description: 'nostrud est esse proident incididunt adipisicing nostrud duis occaecat dolore dolore in',
        category: 'wine',
    },
    {
        _id: '5ff7225b88fc547c7debeb1b',
        picture: 'https://source.unsplash.com/random/125*125',
        name: 'qui',
        color: 'blue',
        description: 'cillum esse adipisicing aute esse duis aliqua eiusmod anim duis aute amet',
        category: 'sport',
    },
];
